SocialNetwork/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('login/', include("smart_mentor.urls")),  # Assurez-vous que 'smart_mentor.urls' contient la route 'login/'
]

urlpatterns += i18n_patterns(
    path('', include("smart_mentor.urls")),
    path('', include("workgroup.urls")),
    path('', include("mentoring_app.urls")),
    path('',include("user_payment.urls")),
    path('', RedirectView.as_view(pattern_name='login', permanent=True)),  # Redirige le chemin racine vers 'login'
    #prefix_default_language=False,  # Ajoutez cette option si vous ne voulez pas de préfixe pour la langue par défaut
)

urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentoring_app/urls.py
from django.urls  import path

from . import views


urlpatterns = [
    path('mentoring_page/',views.mentoring_page,name='mentoring_page'),
    path('user_request/<int:notification_id>/', views.user_request_view, name='user_request'),
    path('register_page/',views.register_page,name='register_page'),
    path('send_request/', views.send_request, name='send_request'),
    path('result/', views.result_page, name='result_page'),
    path('evaluate/', views.evaluate_answers, name='evaluate'),
    path('waiting/', views.waiting_page, name='waiting'),
    path('notifications/', views.all_notifications, name='all_notifications'),
    path('matching_optimized/', views.optim_find, name='matching_optim'),
    path('mentee_page/', views.mentee_page, name='mentee_page'),
    path('mentor_page/', views.mentor_page, name='mentor_page'),
    path('redirect_mentor/', views.redirect_mentor, name='redirect_mentor'),
    path('my_page/', views.my_page, name='my_page'),
    path('coaching_request/<int:request_id>/', views.coaching_request, name='coaching_request'),
    path('availability/', views.availability_view, name='availability_view'),
    path('availability_dates',views.availability_dates,name='availability_dates'),
    path('delete_availability/<int:slot_id>/', views.delete_availability, name='delete_availability'),
    ]

workgroup/urls.py
from django.urls  import path

from . import views


urlpatterns = [
    path('revision_group/',views.revision_group,name='revision_group'),
    path('assistant-endpoint/<int:workgroup_id>/', views.assistant_endpoint, name='assistant_endpoint'),
    path('search',views.search_view,name='search'),
    path('send_invitation/', views.send_invitation, name='send_invitation'),
    path('get-notifications/', views.get_notifications, name='get-notifications'),
    path('notifications/<int:notification_id>/', views.notification_detail, name='notification_detail'),
    path('mark_notification_as_read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('notifications/clear_all/', views.clear_all_notifications, name='clear_all_notifications'),
    path('join_workgroup/<int:workgroup_id>/',views.join_workgroup,name='join_workgroup'),
    path('workgroups/<int:pk>/accept-invitation/', views.accept_invitation, name='accept_invitation'),
    path('workgroups/<int:pk>/refuse-invitation/', views.refuse_invitation, name='refuse_invitation'),
    path('notifications/accept-join/<int:notification_id>/', views.accept_join, name='accept_join'),
    path('notifications/deny-join/<int:notification_id>/', views.deny_join, name='deny_join'),
    path('create-workgroup/', views.create_workgroup, name='create_workgroup'),
    path('workgroups/<int:pk>/', views.workgroup_detail, name='workgroup_detail'),
    path('edit_workgroup/<int:pk>/', views.edit_workgroup, name='edit_workgroup'),
    path('workgroups/', views.workgroup_list, name='workgroup_list'),
    path('delete_workgroup/<int:pk>/', views.delete_workgroup, name='delete_workgroup'),
    path('workgroups/<int:workgroup_id>/create-chat/', views.create_chat_room, name='create_chat_room'),
    path('chat-room/<int:chat_room_id>/', views.chat_room, name='chat_room'),
]

mentoring_app/models.py
from django.conf import settings
from django.db import models

from smart_mentor.models import Profile


# Create your models here.
class Matching(models.Model):
    Fields = models.CharField(max_length=100)
    Degree = models.CharField(max_length=100)
    Skills = models.CharField(max_length=100)
    Objectives = models.CharField(max_length=100)
    Job = models.CharField(max_length=100)
    PersonalityDescription = models.CharField(max_length=100)

    def __str__(self):
        return self.Fields

from django.contrib.auth.models import User

class Mentor(models.Model):
    DEGREE_CHOICES = (
        ('BAC', 'Baccalauréat'),
        ('BTS', 'BTS'),
        ('DUT', 'DUT'),
        ('LIC', 'Bachelor/Licence'),
        ('MAS', 'Master'),
        ('DOC', 'PHD/Doctorat'),
    )

    Fields = models.CharField(max_length=100)
    Degree = models.CharField(max_length=100, choices=DEGREE_CHOICES)
    Skills = models.CharField(max_length=100)
    Objectives = models.CharField(max_length=100)
    Job = models.CharField(max_length=100)
    PersonalityDescription = models.CharField(max_length=100, blank=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.Fields

class Availability(models.Model):
    mentor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    day_of_week = models.CharField(max_length=10)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return f"{self.user.username} available on {self.day_of_week} from {self.start_time} to {self.end_time}"

class CoachingRequest(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('declined', 'Declined'),
    )

    mentor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='coaching_requests_mentor', on_delete=models.CASCADE)
    mentee = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='coaching_requests_mentee', on_delete=models.CASCADE)
    selected_dates = models.JSONField()  # Utilisez JSONField pour stocker une liste de dates
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    
     # DateField pour stocker la date de la session de coaching.
    date = models.DateField(auto_now_add=True)
    available_dates = models.ManyToManyField('Availability')

    # TimeField pour stocker l'heure de la session de coaching.
    time = models.TimeField(auto_now=True)

    def __str__(self):
        return f"Coaching request from {self.mentee} to {self.mentor} - Status: {self.status}"


class Response(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return f"{self.user.username} - {self.question}"

class Notification(models.Model):
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='notifications')
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='sent_notifications')
    workgroup = models.ForeignKey('workgroup.WorkGroup', on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=255)
    body = models.TextField()
    read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    coaching_request_id = models.IntegerField(null=True, blank=True)
    TYPE_CHOICES = (
        ('invitation', 'Invitation'),
        ('join_request', 'Join Request'),
        ('coaching_request', 'Coaching Request'),
        # Autres types si nécessaire
        ('room_launched','Room launched'),
        ('mentor_promotion', 'Mentor Promotion'),
	('renewal_reminder', 'Renewal Reminder'),
        ('premium_status_change','Premium Status'),
        ('follow','Follow'),
    )
    type = models.CharField(max_length=50, choices=TYPE_CHOICES, default='invitation')

    def __str__(self):
        return f'Notification to {self.recipient.username} - {self.type}'

mentoring_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


from .models import Matching, Availability, CoachingRequest


class MatchingForm(forms.ModelForm):
    class Meta:
        model = Matching
        fields = ['Fields', 'Degree', 'Skills', 'Objectives', 'Job', 'PersonalityDescription']

from .models import Mentor  # Assurez-vous d'importer le modèle Mentor

class MentorForm(forms.ModelForm):
    class Meta:
        model = Mentor
        fields = ['Fields', 'Degree', 'Skills', 'Objectives', 'Job', 'PersonalityDescription']

class AvailabilityForm(forms.ModelForm):
    class Meta:
        model = Availability
        fields = ['day_of_week', 'start_time', 'end_time']

class CoachingRequestForm(forms.ModelForm):
    class Meta:
        model = CoachingRequest
        fields = ['mentor', 'mentee']

templates/mentoring_app/availability_dates.html
{% extends 'base_site.html' %}
{% load i18n %}
{% load static %}

{% block navbar %}
    {% include 'nav_mentoring.html' %}
{% endblock %}

{% block content %}
    <div class="availability-container">
        <h2>{% trans 'Your Availability Schedule' %}</h2>
        <div class="availability-cards">
            {% for slot in availability_slots %}
                <div class="availability-card">
                    <div class="date">
                        <span class="day">{{ slot.day_of_week }}</span>
                        <a href="{% url 'delete_availability' slot.id %}" class="delete-btn">X</a>
                    </div>
                    <div class="time">
                        <span>{{ slot.start_time }} - {{ slot.end_time }}</span>
                    </div>
                </div>
            {% empty %}
                <p>{% trans 'No availability slots have been set yet.' %}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}


{% block extra_styles %}
    <style>
        .delete-btn {
            float: right;
            color: red;
            cursor: pointer;
            font-weight: bold;
        }
        .availability-container {
            text-align: center;
            margin: 20px;
        }

        .availability-cards {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 20px;
        }

        .availability-card {
            border: 1px solid #ddd;
            border-radius: 10px;
            padding: 20px;
            width: 200px;
            background-color: #f8f8f8;
            box-shadow: 0 2px 5px rgba(0,0,0,0.2);
        }

        .availability-card .date {
            font-size: 1.2em;
            margin-bottom: 10px;
        }

        .availability-card .time {
            font-size: 1em;
            color: #666;
        }
    </style>
{% endblock %}

templates/mentoring_app/coaching_request.html
{% extends "base_site.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'User request' %}{% endblock %}
{% block extra_styles %}
    <style>
        .content-text-color {
            color: #0097B2;
        }
    </style>
{% endblock %}

{% block navbar %}
{% include 'nav_mentoring.html' %}
{% endblock %}

{% block content %}
    <!-- Section de gestion des demandes de coaching -->
    <section class="container mt-5 content-text-color">
        <h2>{% trans 'Managing coaching sessions'%}</h2>
        <p>{% trans 'You can accept or decline coaching requests here:' %}</p>

        <table class="table table-bordered table-striped content-text-color">
            <thead>
            <tr>
                <th>{% trans 'Mentore' %}</th>
                <th>{% trans 'Date' %}</th>
                <th>{% trans 'Time' %}</th>
                <th>{% trans 'Status' %}</th>
                <th>{% trans 'Actions' %}</th>
            </tr>
            </thead>
            <tbody>
            {% if coaching_requests %}
                {% for request in coaching_requests %}
                    <tr>
                        <td>{{ request.mentee.first_name }} {{ request.mentee.last_name }}</td>
                        <td>{{ request.date }}</td>
                        <td>{{ request.time }}</td>
                        <td>{{ request.status }}</td>
                        <td>
                            <form method="post" action="{% url 'accept_request' %}">
                                {% csrf_token %}
                                <input type="hidden" name="coaching_request_id" value="{{ request.id }}">
                                <button type="submit" class="btn btn-success">{% trans 'Accept' %}</button>
                            </form>
                            <!-- Formulaire pour refuser la demande -->
                            <form method="post" action="{% url 'reject_request' %}">
                                {% csrf_token %}
                                <input type="hidden" name="coaching_request_id" value="{{ request.id }}">
                                <button type="submit" class="btn btn-danger">{% trans 'Deny' %}</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="5" class="text-center">{% trans 'No applications pending at the moment.' %}</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </section>

{% endblock %}

templates/mentoring_app/evaluation.html
{% extends 'base_site.html' %}
{% load static %}
{% load i18n %}

{% block extra_styles %}
    <style>
        .assessment-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
        }

        .question-answer-block {
            background-color: #f9f9f9;
            padding: 15px;
            margin-bottom: 10px;
            border-radius: 8px;
            border: 1px solid #ddd;
        }

        .question-label, .answer-label {
            display: block;
            margin-bottom: 5px;
        }

        .question-label {
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block navbar %}
    {% include 'nav_mentoring.html' %}
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>{% trans 'Do you confirm your results?' %}</h1>
    </div>
    <form method="post" action="{% url 'waiting' %}" class="assessment-container">
        {% csrf_token %}
        {% for question, answer in answers.items %}
            <div class="question-answer-block">
                <label class="question-label">{{ question }}</label>
                <!-- Champ caché pour la question -->
                <input type="hidden" name="question_{{ forloop.counter }}" value="{{ question }}">
                <!-- Champ modifiable pour la réponse ou caché si vous ne souhaitez pas que l'utilisateur puisse modifier -->
                <input type="text" name="answer_{{ forloop.counter }}" value="{{ answer }}">
            </div>
        {% endfor %}
        <div class="button-group" style="display: flex; justify-content: space-between; margin-top: 20px;">
{#            <button type="button" class="btn btn-secondary" onclick="window.history.back();">{% trans 'Go Back' %}</button>#}
            <button type="submit" class="btn btn-primary">{% trans 'Confirm Answers' %}</button>
        </div>
    </form>

{% endblock %}

templates/mentoring_app/is_mentor.html
{% extends 'base_site.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block navbar %}
    {% include 'nav_mentoring.html' %}
{% endblock %}

{% comment %}{% block extrahead %}
    <!-- Si vous utilisez un CDN, utilisez ces liens -->
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar/index.global.min.js'></script>

    <!-- Sinon, utilisez les fichiers locaux comme ceci -->
    <!-- <link href='{% static "css/fullcalendar.min.css" %}' rel='stylesheet' />
<script src='{% static "js/fullcalendar.min.js" %}'></script> -->
{% endblock %}{% endcomment %}

{% block extra_styles %}
    <style>
        #calendar {
            max-width: 600px;
            margin: 0 auto 20px;
        }

        .fc .fc-timegrid-slot, .fc .fc-timegrid-slot-label {
            height: 2em; /* Réduire la hauteur des créneaux horaires */
        }

        h1{
            text-align: center;
            color: #4ac1f7;
        }

        /* ... autres styles ... */
    </style>
{% endblock %}

{% block content %}
    <h1>{% trans 'Define your availability times here!' %}</h1>
    <div class="container d-flex flex-column align-items-center">
        <form method="post" id="availability-form" class="mb-3 w-100" action="{% url 'availability_view' %}">
            {% csrf_token %}
            <input type="hidden" name="availability_slots" id="availability-slots">
            <!-- Remplacez les champs cachés par des champs textuels pour le débogage -->
            <input type="text" name="day_of_week" id="day_of_week">
            <input type="text" name="start_time" id="start_time">
            <input type="text" name="end_time" id="end_time">

            <div id='calendar' class="w-100 mb-3"></div>
            <div class="w-100 d-flex justify-content-center">
                <button class="btn btn-primary" type="submit">{% trans 'Save Availability' %}</button>
            </div>
        </form>
    </div>
{% endblock %}


{% block extra_scripts %}
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/6.1.10/index.global.min.js'></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
	console.log('{{ calendar_events|escapejs }}'); // Affiche la chaîne avant la conversion
	try {
	    var existingEvents = JSON.parse('{{ calendar_events|escapejs }}');
	} catch(e) {
	    console.error("Erreur lors de la conversion JSON:", e);
	    var existingEvents = []; // Utilisez un tableau vide ou une valeur par défaut
	}

    var existingEvents = JSON.parse('{{ calendar_events|escapejs }}');
    var selectedSlots = [];
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'timeGridWeek',
        selectable: true,
        allDaySlot: false,
        slotDuration: '00:30:00',
        slotLabelInterval: '01:00',
        slotMinTime: '08:00:00',
        slotMaxTime: '18:00:00',
        events: existingEvents,
        select: function(info) {
            var start = info.start;
            var end = info.end;
            var eventId = start.toISOString() + '-' + end.toISOString();

            if (!selectedSlots.some(slot => slot.eventId === eventId)) {
                selectedSlots.push({
                    eventId: eventId,
                    start: start.toISOString(),
                    end: end.toISOString()
                });
                calendar.addEvent({
                    id: eventId,
                    start: start,
                    end: end,
                    color: '#28a745'
                });
            }

            document.getElementById('availability-slots').value = JSON.stringify(selectedSlots);
        },
        eventClick: function(info) {
            var event = info.event;
            var index = selectedSlots.findIndex(slot => slot.eventId === event.id);
            if (index > -1) {
                selectedSlots.splice(index, 1);
                event.remove();
            }

            document.getElementById('availability-slots').value = JSON.stringify(selectedSlots);
        }
    });
    calendar.render();
});

    </script>
{% endblock %}

templates/mentoring_app/matching.html
{% extends 'base_site.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}
{% load custom_filters %}

{% block navbar %}
    {% include 'nav_home.html' %}
{% endblock %}

{% block content %}

    <h1>{% trans 'My Mentor' %}</h1>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}


    {% if predicted_score_optim %}
        <p>{% trans 'Predicted Score:' %}</p>
        <ul>
            {% for mentor_info in predicted_score_optim %}
                <li>
                    {% trans 'Matching with' %} {{ mentor_info.Score|floatformat:2|multiply:100 }}%:
                    <ul>
                        <li>{% trans 'First Name: ' %}{{ mentor_info.FirstName }}</li>
                        <li>{% trans 'Name:' %}{{ mentor_info.LastName }}</li>
                        <li>{% trans 'Skills:'%} {{ mentor_info.Skills }}</li>
                        <li>{% trans 'Job:' %}{{ mentor_info.Job }}</li>
                        <li>{% trans 'Rating: ' %}{{ mentor_info.Rating }}/5</li>
                    </ul>
<button class="btn btn-primary btn-send-request" data-mentor-id="{{ mentor_info.ID }}">{% trans 'Send a request' %}</button>
		                    </li>
                <h1><a class="btn btn-link" href="{% url 'profile' mentor_info.ID %}">{% trans 'View full profile' %}</a></h1>
            {% endfor %}
        </ul>
    {% else %}
    	<p>{% trans 'No mentor found for now' %}</p>
    {% endif %}

{% endblock %}

{% block extra_scripts %}
 <!-- Inclusion de jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $(".btn-primary").click(function() {
            var btn = $(this);
            var mentorId = btn.data('mentor-id');
            // Récupération de la date et de l'heure actuelles si nécessaire
            var currentDate = new Date();
            var dateString = currentDate.toISOString().split('T')[0];  // Format 'YYYY-MM-DD'
            var timeString = currentDate.toTimeString().split(' ')[0];  // Format 'HH:MM:SS'

            $.ajax({
                type: "POST",
                url: "{% url 'send_request' %}",
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    mentor_id: mentorId,
                    mentee_id: '{{ user.id }}', // Assurez-vous que c'est la bonne façon d'obtenir l'ID du mentee
                    date: dateString,
                    time: timeString
                },
                success: function(data) {
                    if(data.success) {
                        btn.text("{% trans 'Request Sent' %} ✔").prop("disabled", true).addClass("btn-success");
// Traiter l'ID de CoachingRequest reçu
                        var coachingRequestId = data.coaching_request_id;
                        if (coachingRequestId) {
                            console.log("ID de CoachingRequest:", coachingRequestId);
                            // Vous pouvez utiliser cet ID ici pour des actions supplémentaires
			    localStorage.setItem('coachingRequestId', coachingRequestId);
                        } else {
                            console.log("ID de CoachingRequest non reçu.");
                        }
                    } else {
                        alert("Error sending request!");
                    }
                },
                error: function() {
                    alert("Error sending request!");
                }
            });
        });
    });
</script>
{% endblock %}

templates/mentoring_app/mentee_page.html
{% extends 'base_site.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'Mentee Page' %}{% endblock %}
{% block extra_styles %}
    <style>
        .card {
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Card shadow for depth */
        }

        .btn-info {
            margin-bottom: 1rem; /* Spacing below the button */
        }

    </style>

{% endblock %}

{% block navbar %}
{% include 'nav_mentoring.html' %}
{% endblock %}

{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="text-center mb-4">
                    <h3>{% trans 'Find your mentor !' %}</h3>
                    <p>{% trans 'Fill in this form to start !' %}</p>
                </div>

                <div class="card p-4">
                    <form method="post" action="{% url 'matching_optim' %}">
                        <div class="form-group">
                            <label for="id_Domains">{% trans 'Fields' %}</label>
                            <input type="text" class="form-control" id="id_Domains" name="Fields" placeholder={% trans "Maths"%}>
                        </div>
                        <div class="form-group">
                            <label for="id_Diplomas">{% trans 'Degree' %}</label>
                            <input type="text" class="form-control" id="id_Diplomas" name="Degree" placeholder={% trans "Licence"%}>
                        </div>
                        <div class="form-group">
                            <label for="id_Skills">{% trans 'Skills' %}</label>
                            <input type="text" class="form-control" id="id_Skills" name="Skills" placeholder={% trans "Compute"%}>
                        </div>
                        <div class="form-group">
                            <label for="id_Career_objectives">{% trans 'Career Objectives' %}</label>
                            <input type="text" class="form-control" id="id_Career_objectives" name="Objectives" placeholder={% trans "Architect"%}>
                        </div>
                        <div class="form-group">
                            <label for="id_Job">{% trans 'Job' %}</label>
                            <input type="text" class="form-control" id="id_Job" name="Job" placeholder={% trans "Student"%}>
                        </div>
                        <div class="form-group">
                            <label for="id_Personality">{% trans 'Personality Description' %}</label>
                            <input type="text" class="form-control" id="id_Personality" name="PersonalityDescription" placeholder={% trans "Humble"%}>
                        </div>

                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">{% trans 'Find' %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block footer %}

{% endblock %}

{% block extra_scripts %}
    {#    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>#}
    {#    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>#}
    {#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>#}
{% endblock %}

templates/mentoring_app/questions_page.html
{% extends 'base_site.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'Questions Page' %}{% endblock %}
{% block extra_styles %}
    <style>
        body {
            background: #f5f5f5;
            font-family: 'Arial', sans-serif;
        }
        form {
            max-width: 600px;
            margin: 40px auto;
            background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .question-label {
            display: block;
            margin-top: 20px;
            font-size: 18px;
            color: #333;
        }
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 20px;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-sizing: border-box; /* Include padding and border in element's width and height */
        }
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 4px;
            cursor: pointer;
            display: block;
            width: 100%;
            color: white;
        }
        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }


    </style>

{% endblock %}

{% block navbar %}
    {% include 'nav_mentoring.html' %}
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>{% trans 'Complete this assessment before continuing' %}</h1>
        <p>{% trans 'You must obtain a minimum score of 7/10 to pass the assessment.' %}</p>
    </div>
    <form method="post" action="{% url 'evaluate' %}">
        {% csrf_token %}
        {% for question in questions %}
            <div>
                <label class="question-label">{{ question }}</label>
                <input type="text" name="answer_{{ forloop.counter }}" required>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">{% trans 'Submit Answers' %}</button>
    </form>
{% endblock %}